-- ============================================================================
-- 1. Extensions
-- ============================================================================
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================================
-- 2. immutable_unaccent
--
-- Postgres marks unaccent() STABLE, but a GENERATED ... STORED column requires
-- an IMMUTABLE expression. Pinning the dictionary by regdictionary makes the
-- call deterministic, which is what lets us wrap it as IMMUTABLE.
--
-- This MUST be defined before the generated column below, otherwise the
-- ALTER TABLE fails with "generation expression is not immutable".
-- ============================================================================
CREATE OR REPLACE FUNCTION immutable_unaccent(text) RETURNS text AS
$$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $$
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT;

-- ============================================================================
-- 3. Schema (generated by `prisma migrate diff --from-empty --to-schema`)
-- ============================================================================

-- CreateEnum
CREATE TYPE "Role" AS ENUM ('admin', 'user', 'viewer');

-- CreateEnum
CREATE TYPE "DocumentStatus" AS ENUM ('uploaded', 'processing', 'completed', 'failed');

-- CreateEnum
CREATE TYPE "TextSource" AS ENUM ('native', 'pdf_text', 'docx', 'vision');

-- CreateTable
CREATE TABLE "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "passwordHash" TEXT NOT NULL,
    "role" "Role" NOT NULL DEFAULT 'viewer',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Document" (
    "id" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "mimeType" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "storagePath" TEXT NOT NULL,
    "ownerId" TEXT NOT NULL,
    "status" "DocumentStatus" NOT NULL DEFAULT 'uploaded',
    "error" TEXT,
    "documentType" TEXT,
    "typeConfidence" DOUBLE PRECISION,
    "language" TEXT,
    "title" TEXT,
    "summary" TEXT,
    "textContent" TEXT,
    "textSource" "TextSource",
    "metadata" JSONB,
    "metadataEditedById" TEXT,
    "metadataEditedAt" TIMESTAMP(3),
    "uploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "processedAt" TIMESTAMP(3),

    CONSTRAINT "Document_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Entity" (
    "id" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "normalizedName" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,

    CONSTRAINT "Entity_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "DocumentEntity" (
    "documentId" TEXT NOT NULL,
    "entityId" TEXT NOT NULL,
    "mentionText" TEXT NOT NULL,
    "charStart" INTEGER,
    "charEnd" INTEGER,
    "confidence" DOUBLE PRECISION,

    CONSTRAINT "DocumentEntity_pkey" PRIMARY KEY ("documentId","entityId","mentionText")
);

-- CreateTable
CREATE TABLE "AuditLog" (
    "id" TEXT NOT NULL,
    "actorId" TEXT,
    "action" TEXT NOT NULL,
    "targetType" TEXT,
    "targetId" TEXT,
    "meta" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

-- CreateTable
-- `id` is SERIAL, not TEXT: the insert path never supplies an id.
CREATE TABLE "embedding_chunks" (
    "id" SERIAL NOT NULL,
    "document_id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "parent_content" TEXT,
    "chunking_strategy" TEXT,
    "chunk_index" INTEGER,
    "metadata" JSONB,
    "embedding" vector(1024),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "embedding_chunks_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");

-- CreateIndex
CREATE INDEX "Document_status_idx" ON "Document"("status");

-- CreateIndex
CREATE INDEX "Document_documentType_idx" ON "Document"("documentType");

-- CreateIndex
CREATE INDEX "Document_uploadedAt_idx" ON "Document"("uploadedAt");

-- CreateIndex
CREATE UNIQUE INDEX "Entity_type_normalizedName_key" ON "Entity"("type", "normalizedName");

-- CreateIndex
CREATE INDEX "DocumentEntity_entityId_idx" ON "DocumentEntity"("entityId");

-- CreateIndex
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");

-- CreateIndex
CREATE INDEX "embedding_chunks_document_id_idx" ON "embedding_chunks"("document_id");

-- AddForeignKey
ALTER TABLE "Document" ADD CONSTRAINT "Document_ownerId_fkey" FOREIGN KEY ("ownerId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DocumentEntity" ADD CONSTRAINT "DocumentEntity_documentId_fkey" FOREIGN KEY ("documentId") REFERENCES "Document"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "DocumentEntity" ADD CONSTRAINT "DocumentEntity_entityId_fkey" FOREIGN KEY ("entityId") REFERENCES "Entity"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_actorId_fkey" FOREIGN KEY ("actorId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- ============================================================================
-- 4. embedding_chunks -> Document foreign key
--
-- Prisma does not emit this because EmbeddingChunk carries no relation field
-- (the vector column is Unsupported, so the model stays write-only from raw
-- SQL). Deleting a document must take its chunks with it.
-- ============================================================================
ALTER TABLE "embedding_chunks"
  ADD CONSTRAINT "embedding_chunks_document_id_fkey"
  FOREIGN KEY ("document_id") REFERENCES "Document"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;

-- ============================================================================
-- 5. Full-text search column
--
-- Diacritics are folded on the indexed side so a query typed without them
-- ("hop dong") matches text that has them ("hợp đồng"). metadata is folded into
-- the same vector, which is why there is no separate metadata search branch.
--
-- No ivfflat index on embedding_chunks.embedding: the demo corpus is ~13
-- vectors and `lists = 100` would scatter them across mostly-empty lists,
-- so a probe returns arbitrary or empty neighbours. Sequential scan is both
-- faster and correct at this size.
-- ============================================================================
ALTER TABLE "Document"
  ADD COLUMN "search_tsv" tsvector
  GENERATED ALWAYS AS (
    to_tsvector('simple',
      immutable_unaccent(
        coalesce("title", '') || ' ' ||
        coalesce("textContent", '') || ' ' ||
        coalesce("metadata"::text, '')
      ))
  ) STORED;

CREATE INDEX "Document_search_tsv_idx" ON "Document" USING GIN ("search_tsv");
